# Plugin coded by brogabe on discord & GitHub

increase-blocking-damage: 1.25 # Player blocking takes 25% more damage
disallow-enemy-tp: false # Whether players can teleport to enemy land.
anti-bow-boosting: true # Disables bow boosting
disable-enemy-home: true # Disallows homes in enemy land.
admin-permission: 'solarise.admin' # Allows to bypass a lot of limitations.

darkzone-feature:
  enabled: true # Whether this feature is enabled
  world: Apocalypse # The name of the darkzone world
  deny-teleportation: true # Denies essentials & factions teleportation [/f home, /spawn, /f warp, /home, /warp, etc]
  message: '&4&lDARKZONE &cYou cannot do this command here!'
  allowed-cmds:
    - '/msg'
    - '/f c f'
    - '/f c p'
    - '/helpop'

caves-feature:
  enabled: true # Whether the feature is enabled.
  world: 'caves'
  message: '&4&lCAVES &cYou cannot break this here!'
  allowed-break:
    - 'GOLD_ORE'
    - 'COAL_ORE'
    - 'COAL_BLOCK'
    - 'GOLD_BLOCK'
    - 'DIAMOND_BLOCK'
    - 'DIAMOND_ORE'
    - 'REDSTONE_ORE'
    - 'REDSTONE_BLOCK'
    - 'QUARTZ_ORE'
    - 'QUARTZ_BLOCK'
    - 'LAPIS_ORE'
    - 'LAPIS_BLOCK'
    - 'EMERALD_ORE'
    - 'EMERALD_BLOCK'
    - 'IRON_ORE'
    - 'IRON_BLOCK'