# Plugin coded by brogabe on discord & GitHub

increase-blocking-damage: 1.25 # Player blocking takes 25% more damage
disallow-enemy-tp: false # Whether players can teleport to enemy land.
anti-bow-boosting: true # Disables bow boosting
disable-enemy-home: true # Disallows homes in enemy land.
admin-permission: 'solarise.admin' # Allows to bypass a lot of limitations.
disable-apple-resistance: false # Whether to disable resistance from god apples.

protection-nerf:
  enabled: true
  nerf-per-piece: 6.25

sharpness-buff:
  enabled: true
  amount: 5 # The percentage increase in damage for sharpness.

outpost-boost:
  enabled: true
  name: 'Guardian'
  damage-boost: 5 # Boost damage in water
  damage-reduction: 5 # Take less damage in water
  eco-boost:
    name: "Guardian"
    amount: 5 # How much percentage should money be boosted [ManticRods, ManticSwords, ManticHoes]

darkzone-feature:
  enabled: true # Whether this feature is enabled
  world: Darkzone # The name of the darkzone world
  deny-teleportation: true # Denies essentials & factions teleportation [/f home, /spawn, /f warp, /home, /warp, etc]
  message: '&4&lDARKZONE &cYou cannot do this command here!'
  allowed-cmds:
    - '/msg'
    - '/f c f'
    - '/f c p'
    - '/helpop'
    - '/near'
    - '/fish top'
    - '/upgrade'
    - '/f coords'
    - '/feed'
    - '/f map off'
    - '/f list'
    - '/koth'
    - '/koth schedule'
    - '/koth gui'
    - '/f money withdraw'
    - '/f who'
    - '/f money bal'
    - '/f money deposit'
    - '/f money'
    - '/f money w'
    - '/eat'
    - '/r'
    - '/shards pay'
    - '/bal'
    - '/tell'
    - '/f top'
    - '/f money b'
    - '/f money d'
    - '/outpost'
    - '/staff'
    - '/v'
    - '/sc'
    - '/gmc'
    - '/gms'
    - '/ban'
    - '/mute'
    - '/freeze'
    - '/giveaway join'
    - '/poll'
    - '/polls'
